name: Bandit

on:
  push:
    branches: [ "feature/testing1" ]
  pull_request:
    branches: [ "feature/testing1" ]
  schedule:
    - cron: '43 10 * * 1'

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run Bandit and output markdown
      - name: Run Bandit
        run: bandit -r . -f markdown -o bandit.md || true

      # Post (or update) Bandit report as a sticky PR comment
      - name: Post Bandit Report to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: bandit.md
